=== ywangd/oeebde/bderules.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="BdeRules">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Validations" />
                <xs:element ref="Sumups" />
                <xs:element ref="Reporting" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Validations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rules" type="RulesType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="RulesType">
        <xs:sequence>
            <xs:element name="Rule" maxOccurs="unbounded" >
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Code" type="xs:integer" />
                        <xs:element name="Description" type="xs:string" />
                    </xs:all>
                    <xs:attribute name="Name" type="xs:string" use="required" />
                    <xs:attribute name="Function" type="xs:NMTOKEN" use="required" />
                    <xs:attribute name="Module" type="xs:NMTOKEN" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="Sumups">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rules" type="SumupRulesType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SumupRulesType" >
        <xs:sequence>
            <xs:element name="StartRules" type="SumupRuleType" />
            <xs:element name="TerminateRules" type="SumupRuleType" />
            <xs:element name="EndRules" type="SumupRuleType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SumupRuleType">
        <xs:sequence>
            <xs:element name="Rule" type="RuleType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RuleType">
        <xs:sequence>
            <xs:element ref="Variables" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Function" type="xs:NMTOKEN" use="required" />
        <xs:attribute name="Module" type="xs:NMTOKEN" use="required" />
    </xs:complexType>

    <xs:element name="Reporting" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rules" type="ReportingRulesType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ReportingRulesType">
        <xs:sequence>
            <xs:element name="Rule" type="RuleType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Variables">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Variable" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Variable">
        <xs:complexType>
            <xs:attribute name="Name" type="xs:NMTOKEN" use="required" />
            <xs:attribute name="DefaultValue" type="xs:string" use="required" />
            <xs:attribute name="Type" type="xs:NMTOKEN" use="required" />
            <xs:attribute name="List" type="xs:NMTOKEN" use="required" />
        </xs:complexType>
    </xs:element>


</xs:schema>

=== ywangd/oeebde/bderules.xml
<?xml version="1.0" encoding="UTF-8"?>
<BdeRules xsi:noNamespaceSchemaLocation="bderules.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Validations>
		<Rules>
			<Rule Name="RCode" Module="validationrules" Function="rule_1">
				<Code>1</Code>
				<Description>Record code not in master table</Description>
			</Rule>
			<Rule Name="ECode" Module="validationrules" Function="rule_2">
				<Code>2</Code>
				<Description>Equipment code not in master table</Description>
			</Rule>
			<Rule Name="ACode" Module="validationrules" Function="rule_3">
				<Code>3</Code>
				<Description>Activity code not in master table</Description>
			</Rule>
			<Rule Name="FACodeZeroJobID" Module="validationrules"
				Function="rule_5">
				<Code>5</Code>
				<Description>First significant Activity code has a zero Job ID
				</Description>
			</Rule>
			<Rule Name="FACodeNotMRor@95" Module="validationrules"
				Function="rule_6">
				<Code>6</Code>
				<Description>First significant Activity code not MR or @95
				</Description>
			</Rule>
			<Rule Name="ECodeChanges" Module="validationrules" Function="rule_8">
				<Code>8</Code>
				<Description>Equipment code not consistent</Description>
			</Rule>
			<Rule Name="TSLess" Module="validationrules" Function="rule_9">
				<Code>9</Code>
				<Description>Timestamp is less than the prior record</Description>
			</Rule>
			<Rule Name="TSFuture" Module="validationrules" Function="rule_10">
				<Code>10</Code>
				<Description>Timestamp is in the future</Description>
			</Rule>
			<Rule Name="ITLess" Module="validationrules" Function="rule_12">
				<Code>12</Code>
				<Description>Impression Total is less than the prior record
				</Description>
			</Rule>
			<Rule Name="ITOutbound" Module="validationrules" Function="rule_14">
				<Code>14</Code>
				<Description>Impression Total not in range of 1-999 million
				</Description>
			</Rule>
			<Rule Name="No@95" Module="validationrules" Function="rule_15">
				<Code>15</Code>
				<Description>File contains no @95</Description>
			</Rule>
		</Rules>
	</Validations>
	<Sumups>
		<Rules>
			<StartRules>
				<Rule Name="Whenever" Module="sumuprules" Function="rule_SR_Whenever"><!--Start whenever the corresponding codes are read.--><Variables>
	<Variable Name="onlyif" Type="str" List="true" DefaultValue=""></Variable>
	<Variable Name="ifnot" Type="str" List="true" DefaultValue=""></Variable>
	</Variables></Rule>
				<Rule Name="OnCode" Module="sumuprules" Function="rule_SR_OnCode"><!--Start only when A specific code is read.-->
				<Variables>
	<Variable Name="onlyif" Type="str" List="true" DefaultValue=""></Variable>
	<Variable Name="ifnot" Type="str" List="true" DefaultValue=""></Variable>
	</Variables>
				</Rule>
				<Rule Name="W-up" Module="sumuprules" Function="rule_SR_Wup"><!--Specialized for W-up only. Working based on the On/Off status of the W-up codes.-->
				</Rule>
			</StartRules>
			<TerminateRules>
				<Rule Name="All" Module="sumuprules" Function="rule_TR_All"><!--Terminate all other running sumups.--><Variables>
				<Variable Name="except" Type="str" List="true" DefaultValue=""></Variable></Variables>
				</Rule>
				<Rule Name="None" Module="sumuprules" Function="rule_TR_None"><!--Do NOT terminate any other running sumups.--></Rule>
			</TerminateRules>
			<EndRules>
				<Rule Name="ByOthers" Module="sumuprules" Function="rule_ER_ByOthers"><!--The end of this sumup is triggered by other sumups.--></Rule>
				<Rule Name="OnCode" Module="sumuprules" Function="rule_ER_OnCode"><!--The end of this sumup is triggered on A specific code.--></Rule>
				<Rule Name="W-up" Module="sumuprules" Function="rule_ER_Wup"><!--Specialized for W-up only. The end of this sumup is based on the On/Off Status of the W-up codes.-->
				</Rule>
			</EndRules>
		</Rules>
	</Sumups>
	<Reporting>
		<Rules>
			<Rule Name="None" Module="reportingrules" Function="rule_None"><!--Simply add this sumup to the reporting and do nothing else.--></Rule>
			<Rule Name="Concatenate" Module="reportingrules" Function="rule_Concatenate"><!--Try concatenate its previous and next sumups if itself is a trivial sumup.-->
			<Variables>
			<Variable Name="SIG_DURATION" Type="float" List="false" DefaultValue="0.08333"></Variable>
			<Variable Name="SIG_IMPCOUNT" Type="int" List="false" DefaultValue="20"></Variable>
			</Variables>
			</Rule>
			<Rule Name="Convert" Module="reportingrules" Function="rule_Convert"><!--Convert the sumup from one category to another category.-->
			<Variables>
			<Variable Name="to_sumup" Type="str" List="false" DefaultValue=""></Variable>
			<Variable Name="else_sumup" Type="str" List="false" DefaultValue=""></Variable>
			<Variable Name="onlycodes" Type="str" List="true" DefaultValue=""></Variable>
			</Variables></Rule>
			<Rule Name="MergeAdjacent" Module="reportingrules" Function="rule_MergeAdjacent"><!--Merge adjacent sumups if they are from the same category.--></Rule>
			
		</Rules>
	</Reporting>
</BdeRules>
